[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[scrolling]
history = 0

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
